- include_vars: datadog.yml

- file: name=/etc/datadog/conf.d mode=0755 owner=root group=root state=directory

- name: create /etc/datadog/datadog.conf
  template:
    src: etc/datadog/datadog.conf.j2
    dest: /etc/datadog/datadog.conf
    owner: root
    group: root
    mode: 0755

- name: create /etc/datadog/conf.d/docker_daemon.yaml
  copy:
    src: etc/datadog/conf.d/docker_daemon.yml
    dest: /etc/datadog/conf.d/docker_daemon.yml
    owner: root
    group: root
    mode : 0755

- name: create /etc/systemd/system/dd-agent.service
  template:
    src: etc/systemd/system/dd-agent.service.j2
    dest: /etc/systemd/system/dd-agent.service
    owner: root
    group: root
    mode: 0755

- name: enable datadog agent
  systemd:
    name: dd-agent.service
    enabled: yes
    state: started
