- include_vars: newrelic.yml

- name: Add New Relic repo key
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    id: 548C16BF
    state: present

- name: Add New Relic repository
  copy:
    content: "deb http://apt.newrelic.com/debian/ newrelic non-free"
    dest: /etc/apt/sources.list.d/newrelic.list
    owner: root
    group: root
    mode: 0644
  register: newrelic_repo

- name: apt-get update
  apt:
    update_cache: yes
  when: newrelic_repo.changed

- name: Install New Relic Sysmond
  apt:
    pkg: newrelic-sysmond
    update_cache: yes
    cache_valid_time: 86400
    state: latest
  notify:
    - Restart New Relic

- name: Configure New Relic Sysmond
  template:
    src: etc/newrelic/nrsysmond.cfg
    dest: /etc/newrelic/nrsysmond.cfg
    group: newrelic
    owner: root
    mode: 0640
  notify:
    - Restart New Relic

- name: Add the newrelic user to the docker group
  user:
    name: newrelic
    groups: docker
    append: yes
  notify:
    - Restart New Relic

- name: Ensure New Relic Sysmond is started and enabled
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes

- name: Install the New Relic LVM thinpools monitoring plugin
  template:
    src: usr/sbin/newrelic_lv_thinpool.sh
    dest: /usr/sbin/newrelic_lv_thinpool.sh
    group: root
    owner: root
    mode: 0755

- name: Setup cron job to run the New Relic LVM thinpools monitoring plugin
  cron:
    name: /usr/sbin/newrelic_lv_thinpool.sh
    job: /usr/sbin/newrelic_lv_thinpool.sh


