- include_vars: aws_ecs.yml

# Sysctl and iptables are somehow related to AWS's metadata service for
# IAM roles for tasks.
- name: set net.ipv4.conf.all.route_localnet = 1
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    state: present

- name: add rule to iptables nat PREROUTING chain
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:51679

- name: add rule to iptables nat OUTPUT chain
  iptables:
    table: nat
    chain: OUTPUT
    protocol: tcp
    match: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: REDIRECT
    to_ports: 51679

- file: name=/etc/ecs mode=0750 owner=root group=root state=directory

- file: name=/var/lib/ecs_agent/data mode=0750 owner=root group=root state=directory

- file: name=/var/log/ecs mode=0750 owner=root group=root state=directory

- name: make_dockercfg
  shell: /usr/sbin/make_dockercfg {{docker_user|quote}} {{docker_pass|quote}} {{docker_email|quote}} {{docker_registry|quote}}
  register: dockercfg

- name: create ecs.config
  template:
    src: etc/ecs/ecs.config.j2
    dest: /etc/ecs/ecs.config
    mode: 0640
    owner: root
    group: docker

- name: create ecs-agent service
  template:
    src: etc/systemd/system/ecs-agent.service.j2
    dest: /etc/systemd/system/ecs-agent.service
    mode: 0640
    owner: root
    group: root

- file: name=/root/.docker mode=0700 owner=root group=root state=directory

- name: create /root/.docker/config.json
  copy:
    content: "{{ dockercfg.stdout }}"
    dest: /root/.docker/config.json
    mode: 0600
    owner: root
    group: root

- file: name=/home/ubuntu/.docker mode=0700 owner=ubuntu group=ubuntu state=directory

- name: create /home/ubuntu/.docker/config.json
  copy:
    content: "{{ dockercfg.stdout }}"
    dest: /home/ubuntu/.docker/config.json
    mode: 0600
    owner: ubuntu
    group: ubuntu

- name: enable ecs agent
  command: "systemctl enable ecs-agent.service"

- name: start_ecs_agent
  command: "systemctl start ecs-agent.service"
