- include_vars: docker.yml

- apt_key: url='https://download.docker.com/linux/ubuntu/gpg' state=present
  tags:
    - build_ami

- apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable' state=present
  tags:
    - build_ami

- name: create huge pages target
  copy:
    src: etc/systemd/system/disable_transparent_huge_pages.service
    dest: /etc/systemd/system/disable_transparent_huge_pages.service
    owner: root
    group: root
    mode: 0755
  notify:
    - start transparent huge pages target
  tags:
    - build_ami

- name: enable huge pages target
  command: 'systemctl enable disable_transparent_huge_pages.service'
  notify:
    - start transparent huge pages target
  tags:
    - build_ami

# Docker is too swappy.
- sysctl: name=vm.swappiness value=1 state=present

- apt: name=lvm2
  tags:
    - build_ami

- apt: name=thin-provisioning-tools
  tags:
    - build_ami

- apt: name=linux-aws
  tags:
    - build_ami

- apt: name=linux-headers-aws
  tags:
    - build_ami

- apt: name=linux-image-aws
  tags:
    - build_ami


- apt: name=apparmor
  tags:
    - build_ami

- name: create /usr/sbin/make_dockercfg
  copy:
    src: usr/sbin/make_dockercfg
    dest: /usr/sbin/make_dockercfg
    owner: root
    group: root
    mode: 0755
  tags:
    - build_ami

- stat: path=/dev/xvdc
  register: dev_xvdc

- stat: path=/dev/xvdh
  register: dev_xvdh

- lvg: vg=vg0 pvs=/dev/xvdc
  when: dev_xvdc.stat.exists and not dev_xvdh.stat.exists
  register: docker_vg_xvdc

- lvg: vg=vg0 pvs=/dev/xvdh
  when: dev_xvdh.stat.exists
  register: docker_vg_xvdh

- lvol: vg=vg0 lv=pool0-meta size=5%VG
  when: docker_vg_xvdc|changed or docker_vg_xvdh|changed
  register: docker_pool0_tmeta

- lvol: vg=vg0 lv=pool0 size=85%VG
  when: docker_vg_xvdc|changed or docker_vg_xvdh|changed
  register: docker_pool0_tdata

- lvol: vg=vg0 lv=data0 size=5%VG
  when: docker_vg_xvdc|changed or docker_vg_xvdh|changed
  register: docker_lv_data0

- shell: yes | lvconvert --type thin-pool --poolmetadata vg0/pool0-meta vg0/pool0
  when: docker_pool0_tdata|changed and docker_pool0_tmeta|changed
  register: docker_pool0

- file: path=/etc/lvm/profile state=directory owner=root group=root mode=0755

- copy: src=etc/lvm/profile/docker-thinpool.profile dest=/etc/lvm/profile/docker-thinpool.profile owner=root group=root mode=0644

- shell: lvchange --metadataprofile docker-thinpool vg0/pool0

- filesystem: fstype=ext4 dev=/dev/mapper/vg0-data0 opts='-L docker'
  when: docker_lv_data0|changed
  register: docker_fs_data0

- service: name=docker state=stopped
  when: docker_pool0|changed and docker_fs_data0|changed
  
# Make absolutely sure aufs doesn't exist or docker freaks
# https://github.com/docker/docker/issues/14026

- shell: /bin/umount -t aufs -a -f
  ignore_errors: yes
  when: docker_fs_data0|changed

- file: path=/var/lib/docker state=absent
  ignore_errors: yes
  when: docker_fs_data0|changed

- mount: name=/var/lib/docker src='LABEL=docker' fstype=ext4 state=mounted
  when: docker_fs_data0|changed

- name: Install docker-ce
  apt:
    name: "docker-ce={{ docker_version }}*"
  tags:
    - build_ami

- copy: src=etc/docker/daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=0644
  notify:
    - restart_docker

- copy: src=usr/local/bin/cba dest=/usr/local/bin/cba owner=root mode=0755

- name: Adding ubuntu to docker group
  user: name=ubuntu groups=docker append=yes
  tags: 
    - build_ami

- service: name=docker state=started
