- include_vars: logs.yml

# Docker is too swappy.
- sysctl: name=vm.swappiness value=1 state=present

# Install lvm2
- apt: name=lvm2

- stat: path=/dev/xvdc
  register: dev_xvdc
  
- stat: path=/dev/xvdh
  register: dev_xvdh

- lvg:  vg=vg-docker pvs=/dev/xvdc
  when: dev_xvdc.stat.exists and not dev_xvdh.stat.exists
  register: docker_vg_xvdc

- lvg:  vg=vg-docker pvs=/dev/xvdh
  when: dev_xvdh.stat.exists
  register: docker_vg_xvdh

- shell: lvcreate -l 99%FREE --thinpool vg-docker/docker-thinpool0
  when: docker_vg_xvdc|changed or docker_vg_xvdh|changed
  register: docker_lvol0
  notify:
    - restart_docker

- service: name=docker state=stopped
  when: docker_lvol0|changed
  
# Make absolutely sure aufs doesn't exist or docker freaks
# https://github.com/docker/docker/issues/14026

- shell: /bin/umount -t aufs -a -f
  ignore_errors: yes
  when: docker_lvol0|changed

- shell: /bin/umount -f /var/lib/docker/aufs
  ignore_errors: yes
  when: docker_lvol0|changed

- file: path=/var/lib/docker/aufs state=absent
  ignore_errors: yes
  when: docker_lvol0|changed

- copy: src=etc/default/docker dest=/etc/default/docker owner=root group=root mode=0644
  tags:
    - build_ami
  notify:
    - restart_docker

- apt: name=linux-image-extra-{{ansible_kernel}}
  tags: 
    - build_ami

- apt: name=linux-image-extra-virtual
  tags: 
    - build_ami

- apt: name=apparmor
  tags: 
    - build_ami

- apt: name=docker-engine=1.9.1-0~trusty
  tags: 
    - build_ami

- copy: src=etc/init/docker.conf dest=/etc/init/docker.conf owner=root group=root mode=0644
  tags:
    - build_ami
  notify:
    - restart_docker

# Create docker_maid cron job
- copy: src=usr/sbin/docker_maid dest=/usr/sbin/docker_maid owner=root group=root mode=0755
  tags: 
    - build_ami

- cron: name=docker_maid cron_file=docker_maid user=root minute="15" hour="2,3,4,5,8,11,14,17,20,23" job="/usr/sbin/docker_maid"
  tags: 
    - build_ami

- name: Adding ubuntu to docker group
  user: name=ubuntu groups=docker append=yes
  tags: 
    - build_ami

- service: name=docker state=started