- include_vars: empire.yml

- name: "create /etc/empire/dockercfg"
  copy:
    content: "{{ dockercfg.stdout }}"
    dest: /etc/empire/dockercfg
    mode: 0600
    owner: root
    group: root

- template: src=etc/empire/env/empire.env dest=/etc/empire/env/empire.env mode=0640 owner=root group=root

